const CONFIG = {
  reception: {
    docksUnload: 10,
    throughputPerDock: 3000,
    bufferCapacity: 185,
    truckArrivalRate: 45,
  },
  depalletizing: {
    stations: 2,
    timePerPalletSec: 30,
    containerReuse: 0.8,
    containerScrap: 0.2,
  },
  sorting: {
    sorterCount: 10,
    sorterThroughput: 10000,
    pockets: 400,
    pocketCapacity: 500,
    pocketThreshold: 400,
    scannerSuccessRate: 0.95,
    operatorPerSorter: 10,
    operatorThroughput: 1000,
    efficiencyFactor: 0.90,
    pocketBlocks: 40,
    pocketsPerBlock: 10,
  },
  packing: {
    containerMaxItems: 27,
    containerMaxWeight: 30,
    sealTimeSec: 10,
    palletOutSlots: 16,
  },
  shipping: {
    docksLoad: 24,
    truckPalletCapacity: 32,
    truckContainerSlots: 16,
    truckRollCageSlots: 16,
    loadTimeHours: 2,
  },
  items: {
    maxWeight: 10,
    maxSizeMm: 320,
    nonsortRate: 0.05,
    destinations: 400,
  },
  containers: {
    widthMm: 600,
    heightMm: 400,
    depthMm: 400,
    palletInSlots: 20,
  },
  visualization: {
    canvasWidth: 1300,
    canvasHeight: 850,
    dockUnloadWidth: 54,
    dockUnloadHeight: 32,
    dockLoadWidth: 36,
    dockLoadHeight: 20,
    bufferWidth: 64,
    bufferHeight: 120,
    pocketBlockWidth: 28,
    pocketBlockHeight: 14,
    pocketOffset: 32,
  },
};
